-- MySQL Script generated by MySQL Workbench
-- Tue Oct 29 10:36:00 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema App_comercio_eletronico
-- -----------------------------------------------------
-- modelo visual

-- -----------------------------------------------------
-- Schema App_comercio_eletronico
--
-- modelo visual
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `App_comercio_eletronico` ;
USE `App_comercio_eletronico` ;

-- -----------------------------------------------------
-- Table `App_comercio_eletronico`.`Carrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `App_comercio_eletronico`.`Carrinho` (
  `carrinho_id` INT NOT NULL AUTO_INCREMENT,
  `Clientes_id` INT NOT NULL,
  PRIMARY KEY (`carrinho_id`, `Clientes_id`),
  INDEX `fk_Carrinho_Clientes1_idx` (`Clientes_id` ASC) VISIBLE,
  CONSTRAINT `fk_Carrinho_Clientes1`
    FOREIGN KEY (`Clientes_id`)
    REFERENCES `App_comercio_eletronico`.`Clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `App_comercio_eletronico`.`Pagamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `App_comercio_eletronico`.`Pagamentos` (
  `pagamento_id` INT NOT NULL AUTO_INCREMENT,
  `Carrinho_carrinho_id` INT NOT NULL,
  `Carrinho_Clientes_id` INT NOT NULL,
  PRIMARY KEY (`pagamento_id`, `Carrinho_carrinho_id`, `Carrinho_Clientes_id`),
  INDEX `fk_Pagamentos_Carrinho1_idx` (`Carrinho_carrinho_id` ASC, `Carrinho_Clientes_id` ASC) VISIBLE,
  CONSTRAINT `fk_Pagamentos_Carrinho1`
    FOREIGN KEY (`Carrinho_carrinho_id` , `Carrinho_Clientes_id`)
    REFERENCES `App_comercio_eletronico`.`Carrinho` (`carrinho_id` , `Clientes_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `App_comercio_eletronico`.`Status_Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `App_comercio_eletronico`.`Status_Pedido` (
  `pedido_id` INT NOT NULL AUTO_INCREMENT,
  `Pagamentos_pagamento_id` INT NOT NULL,
  PRIMARY KEY (`pedido_id`),
  INDEX `fk_Status_Pedido_Pagamentos1_idx` (`Pagamentos_pagamento_id` ASC) VISIBLE,
  CONSTRAINT `fk_Status_Pedido_Pagamentos1`
    FOREIGN KEY (`Pagamentos_pagamento_id`)
    REFERENCES `App_comercio_eletronico`.`Pagamentos` (`pagamento_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `App_comercio_eletronico`.`Endereços`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `App_comercio_eletronico`.`Endereços` (
  `endereco_id` INT NOT NULL AUTO_INCREMENT,
  `Status_Pedido_pedido_id` INT NOT NULL,
  PRIMARY KEY (`endereco_id`, `Status_Pedido_pedido_id`),
  INDEX `fk_Endereços_Status_Pedido1_idx` (`Status_Pedido_pedido_id` ASC) VISIBLE,
  CONSTRAINT `fk_Endereços_Status_Pedido1`
    FOREIGN KEY (`Status_Pedido_pedido_id`)
    REFERENCES `App_comercio_eletronico`.`Status_Pedido` (`pedido_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `App_comercio_eletronico`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `App_comercio_eletronico`.`Clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(50) NOT NULL,
  `Endereços_endereco_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Clientes_Endereços_idx` (`Endereços_endereco_id` ASC) VISIBLE,
  CONSTRAINT `fk_Clientes_Endereços`
    FOREIGN KEY (`Endereços_endereco_id`)
    REFERENCES `App_comercio_eletronico`.`Endereços` (`endereco_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `App_comercio_eletronico`.`Categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `App_comercio_eletronico`.`Categorias` (
  `categoria_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`categoria_id`));


-- -----------------------------------------------------
-- Table `App_comercio_eletronico`.`Fornecedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `App_comercio_eletronico`.`Fornecedores` (
  `fornecedor_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`fornecedor_id`));


-- -----------------------------------------------------
-- Table `App_comercio_eletronico`.`Produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `App_comercio_eletronico`.`Produtos` (
  `produto_id` INT NOT NULL AUTO_INCREMENT,
  `Categorias_categoria_id` INT NOT NULL,
  `Carrinho_carrinho_id` INT NOT NULL,
  `Carrinho_Clientes_id` INT NOT NULL,
  `Fornecedores_fornecedor_id1` INT NOT NULL,
  PRIMARY KEY (`produto_id`, `Carrinho_carrinho_id`, `Carrinho_Clientes_id`, `Fornecedores_fornecedor_id1`),
  INDEX `fk_Produtos_Categorias1_idx` (`Categorias_categoria_id` ASC) VISIBLE,
  INDEX `fk_Produtos_Carrinho1_idx` (`Carrinho_carrinho_id` ASC, `Carrinho_Clientes_id` ASC) VISIBLE,
  INDEX `fk_Produtos_Fornecedores2_idx` (`Fornecedores_fornecedor_id1` ASC) VISIBLE,
  CONSTRAINT `fk_Produtos_Categorias1`
    FOREIGN KEY (`Categorias_categoria_id`)
    REFERENCES `App_comercio_eletronico`.`Categorias` (`categoria_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produtos_Carrinho1`
    FOREIGN KEY (`Carrinho_carrinho_id` , `Carrinho_Clientes_id`)
    REFERENCES `App_comercio_eletronico`.`Carrinho` (`carrinho_id` , `Clientes_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produtos_Fornecedores2`
    FOREIGN KEY (`Fornecedores_fornecedor_id1`)
    REFERENCES `App_comercio_eletronico`.`Fornecedores` (`fornecedor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `App_comercio_eletronico`.`Vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `App_comercio_eletronico`.`Vendas` (
  `venda_id` INT NOT NULL AUTO_INCREMENT,
  `Pagamentos_pagamento_id` INT NOT NULL,
  `Pagamentos_Carrinho_carrinho_id` INT NOT NULL,
  `Pagamentos_Carrinho_Clientes_id` INT NOT NULL,
  PRIMARY KEY (`venda_id`, `Pagamentos_pagamento_id`, `Pagamentos_Carrinho_carrinho_id`, `Pagamentos_Carrinho_Clientes_id`),
  INDEX `fk_Vendas_Pagamentos1_idx` (`Pagamentos_pagamento_id` ASC, `Pagamentos_Carrinho_carrinho_id` ASC, `Pagamentos_Carrinho_Clientes_id` ASC) VISIBLE,
  CONSTRAINT `fk_Vendas_Pagamentos1`
    FOREIGN KEY (`Pagamentos_pagamento_id` , `Pagamentos_Carrinho_carrinho_id` , `Pagamentos_Carrinho_Clientes_id`)
    REFERENCES `App_comercio_eletronico`.`Pagamentos` (`pagamento_id` , `Carrinho_carrinho_id` , `Carrinho_Clientes_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `App_comercio_eletronico`.`Itens_Vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `App_comercio_eletronico`.`Itens_Vendas` (
  `itens_venda_id` INT NOT NULL AUTO_INCREMENT,
  `Vendas_venda_id` INT NOT NULL,
  `Endereços_endereco_id1` INT NOT NULL,
  `Endereços_Status_Pedido_pedido_id` INT NOT NULL,
  PRIMARY KEY (`itens_venda_id`, `Endereços_endereco_id1`, `Endereços_Status_Pedido_pedido_id`),
  INDEX `fk_Itens_Vendas_Vendas1_idx` (`Vendas_venda_id` ASC) VISIBLE,
  INDEX `fk_Itens_Vendas_Endereços2_idx` (`Endereços_endereco_id1` ASC, `Endereços_Status_Pedido_pedido_id` ASC) VISIBLE,
  CONSTRAINT `fk_Itens_Vendas_Vendas1`
    FOREIGN KEY (`Vendas_venda_id`)
    REFERENCES `App_comercio_eletronico`.`Vendas` (`venda_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Itens_Vendas_Endereços2`
    FOREIGN KEY (`Endereços_endereco_id1` , `Endereços_Status_Pedido_pedido_id`)
    REFERENCES `App_comercio_eletronico`.`Endereços` (`endereco_id` , `Status_Pedido_pedido_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
